version: v0.13.0

dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  allowed_return_urls:
    - http://127.0.0.1:4455
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      config:
        providers:
          - id: mimoto 
            provider: generic
            client_id: 426f78c8-6867-478a-8586-775597af1e35
            client_secret: ASxDaAxGFMKjkjzu85597af1e35
            mapper_url: file:////etc/config/kratos/mappings/oidc.mimoto.jsonnet
            auth_url: https://mimoto-test.pie.azuma-health.tech/connect/auth
            token_url: https://mimoto-test.pie.azuma-health.tech/connect/token
            issuer_url: https://mimoto-test.pie.azuma-health.tech/
            scope:
              - openid
              - urn:telematik:email
              - urn:telematik:versicherter
      enabled: true      

  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m
      after:
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://backend.api/api/login/after
                method: POST
                can_interrupt: true
                body: file:////etc/config/kratos/mappings/oidc.hook.jsonnet

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://backend.api/api/registration/after
                method: POST
                can_interrupt: true
                response:
                   parse: true
                body: file:////etc/config/kratos/mappings/oidc.hook.jsonnet
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

feature_flags:
  use_continue_with_transitions: true
