version: '3.7'

networks:
  sample_network:
    name: sample_network
    driver: bridge
    attachable: true


services:
  postgresd:
    image: postgres:14.1-alpine
    ports:
      - "5439:5432"
    volumes: 
      - pos-psql-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - sample_network

  kratos-migrate:
    depends_on:
      - postgresd
    image: oryd/kratos:v1.1.0
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - sample_network

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.1.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - sample_network

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - sample_network

volumes:
  pos-psql-db:
    driver: local